### ISSUE TITLE
rbindlist error in buildExplainer

### ISSUE THREAD

**Issue by machuck** [AppliedDataSciencePartners/xgboostExplainer#23]
Error in rbindlist(append(list(tree_breakdown), list(leaf_breakdown))) : 
  Item 2 has 3 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.

**Comment by jbohart** [comment]
FYI - had same problem and fixed it by making sure my train data was xgb.DMatrix being passed in.

**Comment by andysw90** [comment]
I had this issue. The CRAN xgboost 1.5.2.1 does not save feature names when saving an xgb dmatrix to file (https://github.com/dmlc/xgboost/issues/1151). If I manually add the feature names back in to the loaded xgb Dmatrix (with `colnames(dmat) <- ` then the issue resolves.
