### ISSUE TITLE
buildExplainer: 'n_first_tree' is deprecated. Use 'trees' instead.

### ISSUE THREAD

**Issue by Quaterion** [AppliedDataSciencePartners/xgboostExplainer#26]
Using xgboostExplainer_0.1 and the sample code from the documentation after calling
explainer = buildExplainer(xgb.model,xgb.train.data, type="binary", base_score = 0.5, n_first_tree = xgb.model$best_ntreelimit - 1)

I get the following error message: 
Creating the trees of the xgboost model...Fehler in parse(text = paste(new_par, "<-", pars[[pars_par]])) : 
  <text>:2:0: unerwartetes Ende der Eingabe
1: trees <- 
   ^
Zusätzlich: Warnmeldung:
'n_first_tree' is deprecated.
Use 'trees' instead.
See help("Deprecated") and help("xgboost-deprecated").

This means that the excample from the current version of the documentation does not work.

**Comment by davidADSP** [comment]
fixed by 10e61bb194b09ac5ac23f54ab632f310fcf6b728
