### ISSUE TITLE
Error in rbindlist(append(list(tree_breakdown), list(leaf_breakdown)))

### ISSUE THREAD

**Issue by gdtrejo** [AppliedDataSciencePartners/xgboostExplainer#42]
I am encountering a problem using the buildExplainer function with my XGBoost model. The error that occurs is:
"Error in rbindlist(append(list(tree_breakdown), list(leaf_breakdown))): Item 2 has 5 columns, inconsistent with item 1 which has 2 columns. To fill missing columns use fill=TRUE."

I think this error originates from the getTreeBreakdown function, where an attempt is made to combine a list of tree breakdowns with a leaf breakdown. The inconsistency in the number of columns is causing the failure.

Possible solution:
It would be useful to review how the tree_breakdown and leaf_breakdown structures are created in the getTreeBreakdown and getLeafBreakdown functions, respectively, and make sure they have a consistent number of columns before trying to combine them with rbindlist.

I would greatly appreciate your help with this problem. I am available to provide any additional information that may be required.

**Comment by Jon77Ruler** [comment]
Did you resolve this? How, please? Seems to still be an issue.  (@gdtrejo)
